# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

sphinx:
  configuration: docs/conf.py   # change if your conf.py is elsewhere

python:
  install:
    - requirements: docs/requirements.txt

