# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev

sphinx:
  configuration: docs/conf.py   # or "conf.py" if your conf.py is at repo root

python:
  install:
    - method: pip
      path: .                   # if you have a Python package; remove if not
    - requirements: docs/requirements.txt

